server:
  port: 8080
  servlet:
    context-path: /bootcamp-santander
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://cayaejeymnsisd:a470180d236b6c6e51f5d51e41ea12c856e96c406d6008575611293c6388a713@ec2-3-224-7-166.compute-1.amazonaws.com:5432/d57uk5d2fdv4ds
    username: cayaejeymnsisd
    password: a470180d236b6c6e51f5d51e41ea12c856e96c406d6008575611293c6388a713
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto Santander Dev Week